name: Makefile CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      run: pacman -Syu gcc git libgit2 base-devel pkgconf sudo fakeroot cmake make curl --noconfirm --needed

    - name: Install cpr
      run: |
          git clone https://github.com/libcpr/cpr
          cd cpr
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCPR_BUILD_TESTS=OFF -DCPR_USE_SYSTEM_CURL=ON
          make
          sudo make install   
    - name: Clean
      run: make clean

    - name: Compile
      run: make
