name: Makefile CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      run: pacman -Syu gcc git libgit2 base-devel pkgconf sudo fakeroot cmake make curl --noconfirm --needed

    - name: Get submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Clean
      run: make clean

    - name: Compile
      run: make
