name: Makefile CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cpr
      run: git clone https://github.com/whoshuu/cpr && cd cpr && mkdir build && cd build && cmake .. && make && sudo make install
    
    - name: Install dependencies
      run: sudo apt-get install -y libgit2 libgit2-dev lib
      
    - name: Clean
      run: make clean

    - name: Compile
      run: make
