name: Makefile CI

on:
  push:
    branches: [ "libalpm-test", "dev", "main" ]
  pull_request:
    branches: [ "libalpm-test", "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      run: pacman -Syu git base-devel sudo fakeroot cmake make --noconfirm --needed

    - name: Get submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Clean
      run: make clean

    - name: Compile
      run: make

    - name: Test taur
      run: ./taur -t
