name: Makefile CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      run: pacman -Syu gcc git libgit2 sudo fakeroot --noconfirm --needed

    - name: Install cpr
      run: |
          git clone https://aur.archlinux.org/cpr.git
          chown -R nobody cpr
          cd pacman-git
          sudo -u nobody makepkg --nocheck
          sudo -u nobody makepkg --packagelist > list
          yes | pacman -U $(cat list)      
    - name: Clean
      run: make clean

    - name: Compile
      run: make
